name: Build and Deploy to GH Pages
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          build_configuration: production
          base_href: /tips/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/tips-of-the-day
